export const LOAD_PASSMAN_DATA_DONE = 'LOAD_PASSMAN_DATA_DONE'
export const LOAD_PASSMAN_DATA_LOADING = 'LOAD_PASSMAN_DATA_LOADING'
export const LOAD_PASSMAN_DATA_ERROR = 'LOAD_PASSMAN_DATA_ERROR'

export const INPUT_PASSMAN_DATA = 'INPUT_PASSMAN_DATA'
export const SHOW_PASSMAN_DATA = 'SHOW_PASSMAN_DATA'
export const HIDE_PASSMAN_DATA = 'HIDE_PASSMAN_DATA'
